### ISSUE TITLE
Question: is it possible to control the gateway?

### ISSUE THREAD

**Issue by svrooij** [quibusus/node-xiaomi-smart-home#1]
This library is a really good start. I want to create something that would publish the realtime notifications of the gateway to my mqtt server, like I've done with [evohome2mqtt](https://github.com/svrooij/evohome2mqtt).

That seems like a scenario that is possible, but would it also be possible to control the gateway light? Or to set the alarm status? Then it would also be possible to make the alarm turn on with an mqtt message. I like the alarm feature, but I dislike the Chinese application 😝

**Comment by quibusus** [comment]
For more info try the code I based my lib on - https://notes.jmsinfor.com/blog/post/admin/Xiaomi-Hub, be sure to check also comments.

As far as I know, nobody reverse-engineered the gateway light/alarm etc. yet and I have no current plans to do that.
