### ISSUE TITLE
How to trigger event data.th

### ISSUE THREAD

**Issue by amoinier** [quibusus/node-xiaomi-smart-home#11]
Hi, I have a aqara temperature/humidity sensor connected to my gateway. I receive heartbeat of gateway but now I try to get data of th sensor but I don't know how trigger event. Do you have an idea ?

**Comment by amoinier** [comment]
For other people, th sensor send datas whend it change ( +- 0.5 for temp and +-6% for humidity)

**Comment by quibusus** [comment]
@amoinier thank you for the info for others. Or you can push the button on the sensor and it triggers sending the data.
