### ISSUE TITLE
Aqara Motion Sensor

### ISSUE THREAD

**Issue by Hamtar0** [quibusus/node-xiaomi-smart-home#14]
Hello ! 

My Aqara Motion Sensor don't appear on message. Is it normal ?

**Comment by Hamtar0** [comment]
Don't know, name is Aqara with motion and lux sensors.
On this module, everything works : https://github.com/marvinroger/node-lumi-aqara
(And it can interact with gateway light... ;) )

I am not a pro developper so I don't really understand all codes... :/

**Comment by quibusus** [comment]
That is weird, the sensors work for me.
- do you have any other xiaomi gadgets? (switch, magnet switch, etc.)
- are you using the latest version (1.2.0 or later)

**Comment by quibusus** [comment]
Update: it looks that they released a new version of the sensor (looking the same as the old one) please upgrade the library and it should work now.

**Comment by Hamtar0** [comment]
Nice ! That's work now.
Now, you can integrate the light data ^^

**Comment by quibusus** [comment]
Great,  I'll close this issue, you can add the PR to one of these or create a new one

https://github.com/quibusus/node-xiaomi-smart-home/issues/15
https://github.com/quibusus/node-xiaomi-smart-home/issues/16

**Comment by Hamtar0** [comment]
Do you have an original motion sensor ? I wan't to know if it communicate the lux and inactivty values like on last Aqara model.
