### ISSUE TITLE
'sensor' can be null here sometimes

### ISSUE THREAD

**Issue by torinnguyen** [quibusus/node-xiaomi-smart-home#19]
I'm not sure sure how to replicate this issue, but I'm getting such error from NodeRed log when I use **node-red-contrib-xiaomi-home**

https://github.com/quibusus/node-xiaomi-smart-home/blob/79e477ccccfc34d3fe1ae47d9c7f8e0b2b9998e0/src/Hub.ts#L119

**Comment by quibusus** [comment]
Hey @torinnguyen, thanks for the report.

Can you do some debugging? Add `console.info(msgBuffer.toString())` before line 119

**Comment by quibusus** [comment]
closing tue to inactivity
