### ISSUE TITLE
how to config 

### ISSUE THREAD

**Issue by Hesamp** [quibusus/node-xiaomi-smart-home#26]
After the implementation, no reaction is found

**Comment by quibusus** [comment]
Please check updated HOWTO, you need to switch on the "development mode" on your gateway http://bbs.xiaomi.cn/t-13198850

**Comment by shumakosik** [comment]
url is not exist
i turn on developer mode with lan communication
please, where i shoul use my token in your code?

**Comment by quibusus** [comment]
try checking here: https://pimatic.org/plugins/pimatic-aqara/

**Comment by quibusus** [comment]
I'm deprecating this module in favor of https://www.home-assistant.io/

Please check it out, it works well with Xiaomi and has much more possibilities 👍
